#!/bin/bash

cargo build --release &&
systemctl --user stop temperature-monitor.service &&
cp ./target/release/temperature-monitor ~/.local/bin/ &&
cp ./temperature-monitor.service ~/.config/systemd/user/ &&
systemctl --user daemon-reload &&
systemctl --user start temperature-monitor.service
