#!/bin/bash

cargo build --release &&
sudo systemctl stop temperature-monitor.service &&
sudo cp ./target/release/temperature-monitor /usr/local/bin/ &&
sudo cp ./temperature-monitor.service /etc/systemd/system/ &&
sudo systemctl daemon-reload &&
sudo systemctl start temperature-monitor.service
